FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

RUN apt-get update -y
RUN apt-get install -y zlib1g-dev wget libbz2-dev liblzma-dev bzip2 make gcc libncurses5-dev \
 automake build-essential cmake curl gawk git gnuplot graphviz libarchive-dev libcurl4-gnutls-dev \
 libhts-dev libncursesw5-dev libvcflib-tools libssl-dev pkg-config python3 python3-dev python3-pip \
 python3-setuptools r-base-core rsync unzip tabix libssl-dev default-jre
RUN apt-get install -y python-is-python3
RUN apt-get install -y samtools bwa bedtools 
RUN pip install pyyaml fpdf

RUN wget -q https://github.com/usadellab/Trimmomatic/files/5854859/Trimmomatic-0.39.zip && unzip Trimmomatic-0.39.zip
RUN printf '#!/bin/bash \
\njava -jar /Trimmomatic-0.39/trimmomatic-0.39.jar "$@"\n' > /usr/local/bin/trimmomatic && chmod u+x /usr/local/bin/trimmomatic

RUN wget -q https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip && unzip snpEff_latest_core.zip
RUN printf '#!/bin/bash \
\njava -jar /snpEff/snpEff.jar $@"\n' > /usr/local/bin/snpEff && chmod u+x /usr/local/bin/snpEff

RUN wget -q https://github.com/broadinstitute/gatk/releases/download/4.2.4.1/gatk-4.2.4.1.zip && unzip gatk-4.2.4.1.zip

COPY ./tools /varpipe/tools
WORKDIR /varpipe/data

ENV PATH=$PATH:/varpipe/tools:/gatk-4.2.4.1

CMD /bin/bash
